spring.datasource.url: jdbc:mysql://b6b950b253bfe0:9d7f2243@eu-cdbr-west-01.cleardb.com/heroku_506b157a228d6ce?useUnicode=true&characterEncoding=utf-8&reconnect=true
#spring.datasource.url: jdbc:mysql://localhost:3306/db_schema?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 1234qwer
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: true

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.liquibase.enabled: false

#spring.servlet.multipart.max-file-size: 1024KB
#spring.servlet.multipart.max-request-size: 1024KB

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005
captcha.deleteTime: 3600000


password.url: http://localhost:8080/login/change-password/